### ISSUE TITLE
Task 4.2.2.3: Plasma x-ray source

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#113]
- [ ] Usage example
- [ ] Data format documentation
- [ ] Produce data (Source intensity or field distribution)
- [ ] Deposit data incl. DOI generation

**Comment by CFGrote** [comment]
@n01r , @bussmann 
hi guys, anything happening here? we're three weeks from the deadline and i would like to avoid a situation like  last time...

a short updated would be nice.

thanks

**Comment by n01r** [comment]
I am extremely sorry for the delay! We're finalizing the report at this moment.

**Comment by bussmann** [comment]
Dear Carsten,
We'll send in the Report today. I am very sorry for the delay. I was traveling the last 3 weeks and could not help with the final draft the way I wanted to.
Best, Michael 

-------- Ursprüngliche Nachricht --------
Von: Carsten Fortmann-Grote <notifications@github.com> 
Datum: 11.09.17  09:25  (GMT+01:00) 
An: eucall-software/simex_platform <simex_platform@noreply.github.com> 
Cc: Michael Bussmann <m.bussmann@hzdr.de>, Mention <mention@noreply.github.com> 
Betreff: Re: [eucall-software/simex_platform] Task 4.2.2.3: Plasma x-ray
  source (#113) 

@n01r , @bussmann

hi guys, anything happening here? we're three weeks from the deadline and i would like to avoid a situation like  last time...
a short updated would be nice.
thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/eucall-software/simex_platform","title":"eucall-software/simex_platform","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/eucall-software/simex_platform"}},"updates":{"snippets":[{"icon":"PERSON","message":"@CFGrote in #113: @n01r , @bussmann \r\nhi guys, anything happening here? we're three weeks from the deadline and i would like to avoid a situation like  last time...\r\n\r\na short updated would be nice.\r\n\r\nthanks"}],"action":{"name":"View Issue","url":"https://github.com/eucall-software/simex_platform/issues/113#issuecomment-328441095"}}}

**Comment by CFGrote** [comment]
no problem, glad to see it's coming along.

carsten
