### ISSUE TITLE
Enable parallel execution of simS2E calculators

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#20]
Develop a strategy how to do parallel backengine execution and implement in Calculators.

**Comment by CFGrote** [comment]
@SergeyYakubov : review attached.
Good work, few comments:
- need testing.
- please document at typical use case, how will the user apply the parallel execution? depending on the answer to this one, i might have more comments.
- add more code comments, pleeeeeeeeeeeaaaaaaaaaaaaase

[review4b9cbff.patch.txt](https://github.com/eucall-software/simex_platform/files/555524/review4b9cbff.patch.txt)

**Comment by SergeyYakubov** [comment]
**Basic idea**
Each calculator is itself responsible for starting his backengine in parallel.

**To start simex in parallel user have to**
1. Similar to a serial job create a python script for simex workflow.
2. Allocate compute resources. Whether it is a batch or interactive job.
3. At this stage the list of allocated resources is known. What we need is a list of nodes. In case of SLURM it is in SLURM_JOB_NODELIST environment variable. Other job managers should have similar variables which we can check as well. Otherwise user has to set SIMEX_JOB_NODELIST variable itself.
4. User starts python <user_script>.py as usual. Simex knows what to do.

**How does simex know what to do**
Having list of nodes we can create a table for each node - node name, number of cores, has GPU or not, ...
Calculators know what kind of parallel job they should start. It can be
- Pure MPI job. Start number of MPI processes=total number of cores (by default)
- Hybrid MPI/OpenMP job. On every node start one MPI process and set OMP_NUM_THREADS to number of cores (by default)
- Pure OpenMP job. Use only one node and set OMP_NUM_THREADS to number of cores on this node (by default).
- GPU job .....

**User can change defaults**
By default simex grabs all available resources. In  99% cases that is what is needed. If not, user can set parameters for each calculator. I can think of a single parameter cpus_per_task that means
- For pure MPI job - number of cpu's per MPI process. Default - cpus_per_task=1, cpus_per_task=MAX will start one MPI process on each node. Can be usefull for memory demanding calculators
- Hybrid MPI/OpenMP - number of threads for each MPI process. Default cpus_per_task=MAX will start one MPI process and all available threads, cpus_per_task=2 will start ncores/2 MPI processes with two threads each, ...
- Pure OpenMP OMP_NUM_THREADS=cpus_per_task (makes little sense though).

**Comment by CFGrote** [comment]
ok. sounds straightforward. do you want to infer/guess the relevant env parameters at build time or at runtime? i guess for small personal clusters, the former makes sense while for big  hpc clusters like maxwell, the latter because available resources vary.

**Comment by SergeyYakubov** [comment]
I would not distinguish between clusters. Should be universal. So, always runtime. If SIMEX_JOB_NODELIST is empty and checking known SLURM, moab, etc variables does not help we can fire _mpirun hostname_ which should give a list of nodes, then ssh to each node and get number of cores. Something like that.

**Comment by CFGrote** [comment]
ok. we should just document all this very well.

**Comment by SergeyYakubov** [comment]
Yes. But in most cases user does not need to do anything. Just start his script. And for developers we'll make it easy by providing function to get all this information.

**Comment by bussmann** [comment]
Guys, we should talk...
