### ISSUE TITLE
Complex target

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#95]

**Comment by bussmann** [comment]
Could you please elaborate?

**Comment by richardbriggs** [comment]
How to implement multi-layer targets for the long pulse experiments. Currently, the easiest solution (and typical experiments) consist of ablating material, sample and window (or no window material). Eg. CH, Sn, LiF, 3 layers. or C, Sn, C, 3 layers.

In some long pulse experiments there is a need for a heat shield from teh X-ray plasma generation during ablation, that would need very thin layers of Au :. Also some targets deposit plastic onto the ablating diamond to increase absorption of the laser: So that target would be: Element(thickness):
CH(4um), C(20um), Au(0.1um), Sn(5um), C(40um).

Creating those types of targets automatically with the current parameters generator for the long pulse experiments needs a bit more thought to allow for more 'expert user' modification, as currently the way the zones are calculated are simple enough for 2 or 3 layers.

**Comment by richardbriggs** [comment]
Have added the option of including 2 layers, before and after the sample layer.

Options are: 

Number of layers = 1 
Ablator

Number of layers = 2
Ablator + Sample

Number of layers = 3
Ablator + layer1 + sample

Number of layers = 4
Ablator + layer1 + sample + layer2

Can enhance later... but issue closed.
